In [1]:
import numpy as np
import cv2

# Set labels of objects
object_label_1 = 'Face_1_Eating_Back'
object_label_2 = 'Face_2_Eating_Back'
object_label_3 = 'Face_3_Eating_Back'

# Load the npy cooords for each face in the frame
f1 = np.load('Output/Data/'+ object_label_1 + '.npy')
f2 = np.load('Output/Data/'+ object_label_2 + '.npy')
f3 = np.load('Output/Data/'+ object_label_3 + '.npy')

# Video path
videoPath = 'Output/videos/';

print("F1:")
print(f1)
print("F2:")
print(f2)
print("F3:")
print(f3)

# Load an avi video to set the anchor points
numAnchorCols = 5+1
numAnchorRows = 5+1

# TODO Loop through the videos and data directories to pull the video frames
# as well as the feature face extraction coords
videoName = 'Eating_Back_rect.avi'
cap = cv2.VideoCapture(videoPath + videoName)

# Get information of the video
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))   
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) 
fp = cap.get(cv2.CAP_PROP_FPS)

# Frame configuration for resizing and visualizing
step = 20
scale_percent = 25/100

print("Frame count = " + str(frame_count));
print("Height / width = " + str(height) + " / " + str(width));
print("Frames per/sec = " + str(fp));

# Loop through the video and pull out every 10th frame
# while(cap.isOpened()):
for i in range(0, frame_count, 20):
#     print("Reading frame [" + str(i) + "]")

    # read the current frame
    cap.set(cv2.CAP_PROP_POS_FRAMES, i) 
#     print("Capture current frame:")
    frame_pos = cap.get(cv2.CAP_PROP_POS_FRAMES)

    ret, frame = cap.read()    

    if ret == True:

        # Convert color image into grayscale image
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        height = int(gray.shape[0]*scale_percent)
        width = int(gray.shape[1]*scale_percent)
        dim = (width, height)
        print("Frame [ " + str(frame_pos) + " ], (" + str(height) + ", " + str(width) + ")")

        # Create the anchors in the frame
        colSpacing = int(width/numAnchorCols)
        rowSpacing = int(height/numAnchorRows)
        print("Row spacing = " + str(colSpacing))
        print("Col spacing = " + str(rowSpacing))
        
        # Create the coord points for the cols
        colAnchorPts = list(range(colSpacing, width, colSpacing))
        rowAnchorPts = list(range(rowSpacing, height, rowSpacing))
        print("Column anchor pts:")
        print(colAnchorPts)
        print("Row anchor pts:")
        print(rowAnchorPts)
        print("\n")

        # resize the frame for viewing
        rimg = cv2.resize(gray, dim, interpolation = cv2.INTER_AREA)
        
        # loop through anchor pts and insert small circles
        for m in range(len(rowAnchorPts)):
            for n in range(len(colAnchorPts)):
                circleCenter = (colAnchorPts[m], rowAnchorPts[n])
                print("Circle center = " + str(circleCenter))
                circleRadius = 3
                circleColor = (0,255,0)
                cv2.circle(rimg, circleCenter, circleRadius, circleColor, -1)

        cv2.imshow('Video Frame', rimg)
        
    cv2.waitKey(1)
#     else: 
#         break;

# Press 'q' to close all windows
# & 0xFF == ord('q'):
#     break
        
# Press 'q' to close all windows
# if cv2.waitKey(1) & 0xFF == ord('q'):
#     break          
cap.release()
# cv2.waitKey(1) & 0xFF == ord('q')
cv2.destroyAllWindows()


F1:
[345 263 127 188]
F2:
[923 283 124 148]
F3:
[1335  345  112  175]
Frame count = 507
Height / width = 1080 / 1920
Frames per/sec = 59.9
Frame [ 0.0 ], (270, 480)
Row spacing = 80
Col spacing = 45
Column anchor pts:
[80, 160, 240, 320, 400]
Row anchor pts:
[45, 90, 135, 180, 225]


Circle center = (80, 45)
Circle center = (80, 90)
Circle center = (80, 135)
Circle center = (80, 180)
Circle center = (80, 225)
Circle center = (160, 45)
Circle center = (160, 90)
Circle center = (160, 135)
Circle center = (160, 180)
Circle center = (160, 225)
Circle center = (240, 45)
Circle center = (240, 90)
Circle center = (240, 135)
Circle center = (240, 180)
Circle center = (240, 225)
Circle center = (320, 45)
Circle center = (320, 90)
Circle center = (320, 135)
Circle center = (320, 180)
Circle center = (320, 225)
Circle center = (400, 45)
Circle center = (400, 90)
Circle center = (400, 135)
Circle center = (400, 180)
Circle center = (400, 225)
Frame [ 20.0 ], (270, 480)
Row spacing = 80
Col spacing

Frame [ 220.0 ], (270, 480)
Row spacing = 80
Col spacing = 45
Column anchor pts:
[80, 160, 240, 320, 400]
Row anchor pts:
[45, 90, 135, 180, 225]


Circle center = (80, 45)
Circle center = (80, 90)
Circle center = (80, 135)
Circle center = (80, 180)
Circle center = (80, 225)
Circle center = (160, 45)
Circle center = (160, 90)
Circle center = (160, 135)
Circle center = (160, 180)
Circle center = (160, 225)
Circle center = (240, 45)
Circle center = (240, 90)
Circle center = (240, 135)
Circle center = (240, 180)
Circle center = (240, 225)
Circle center = (320, 45)
Circle center = (320, 90)
Circle center = (320, 135)
Circle center = (320, 180)
Circle center = (320, 225)
Circle center = (400, 45)
Circle center = (400, 90)
Circle center = (400, 135)
Circle center = (400, 180)
Circle center = (400, 225)
Frame [ 240.0 ], (270, 480)
Row spacing = 80
Col spacing = 45
Column anchor pts:
[80, 160, 240, 320, 400]
Row anchor pts:
[45, 90, 135, 180, 225]


Circle center = (80, 45)
Circle center = (80

Frame [ 460.0 ], (270, 480)
Row spacing = 80
Col spacing = 45
Column anchor pts:
[80, 160, 240, 320, 400]
Row anchor pts:
[45, 90, 135, 180, 225]


Circle center = (80, 45)
Circle center = (80, 90)
Circle center = (80, 135)
Circle center = (80, 180)
Circle center = (80, 225)
Circle center = (160, 45)
Circle center = (160, 90)
Circle center = (160, 135)
Circle center = (160, 180)
Circle center = (160, 225)
Circle center = (240, 45)
Circle center = (240, 90)
Circle center = (240, 135)
Circle center = (240, 180)
Circle center = (240, 225)
Circle center = (320, 45)
Circle center = (320, 90)
Circle center = (320, 135)
Circle center = (320, 180)
Circle center = (320, 225)
Circle center = (400, 45)
Circle center = (400, 90)
Circle center = (400, 135)
Circle center = (400, 180)
Circle center = (400, 225)
Frame [ 480.0 ], (270, 480)
Row spacing = 80
Col spacing = 45
Column anchor pts:
[80, 160, 240, 320, 400]
Row anchor pts:
[45, 90, 135, 180, 225]


Circle center = (80, 45)
Circle center = (80